### PR TITLE
Support for Apache Tinkerpop 3

### PR DESCRIPTION
**Pull request by amcp**
I upgraded versions of the underlying graph database implementations and the TP version. I removed Sparksee for the time being as they do not support TP3 yet. I will refactor for TP3 commonalities between Orient and TitanDB. Still need to do a test run.

### CODE REVIEW

**Comment by lvca** [comment]
OrientDB doesn't support tp3 yet.

**Comment by amcp** [comment]
I will rely on the third party plugin orientdb-gremlin until such time that OrientDB themselves support TP3.

**Comment by sarovios** [comment]
Please let me know when you have done a test run and after we can merge that.

**Comment by lvca** [comment]
This is a benchmark and a 3rd party plugin couldn't be optimized for speed, so I think it's not a good idea.

**Comment by amcp** [comment]
Given the absence of official support, this is a viable way to get an artifact that compiles. When official support is announced, I will replace the use of the plugin with whatever OrientDB does to support TP3 officially. The changes should be minimal, because both the plugin and OrientDB will implement TP3 at that point. I will add a TODO to check and replace with the official TP3 support.

**Comment by lvca** [comment]
My point is that this is a benchmark, so comparing OrientDB with an non official driver is not fair.

**Comment by sarovios** [comment]
I agree. For the benchmark to be fair we should use the native apis of each db if possible or at least officially supported drivers.

**Comment by amcp** [comment]
I agree with Sotori and Luca, the benchmark needs to use official libs. That is why we should keep this work in another branch (eg, tp3), not master, and if OrientDB officially supports TP3, then I can swap out orient-gremlin with the official implementation and we can merge back to master.

**Comment by amcp** [comment]
I will close this and open another a Pull Request for a different branch (not master).

**Comment by amcp** [comment]
Seems like i can't specify a branch that doesn't exist in upstream, so i am reopening this PR.
Sotiri, when I am ready can you merge this into a new branch called TP3? That way, we preserve the native OrientDB TP2.6 implementation on master until their TP3 is ready.

**Comment by sarovios** [comment]
Sounds good. I just created a new branch called tp3. Feel free to use it.

**Comment by amcp** [comment]
ok, I'm closing this and opening a new PR on tp3

**Pull request closed without merging**
